//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorMWS.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfiguratorMWS.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить запись.
        /// </summary>
        internal static string AddARecord {
            get {
                return ResourceManager.GetString("AddARecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Усреднение: .
        /// </summary>
        internal static string Averaging {
            get {
                return ResourceManager.GetString("Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временной интервал, за который производится усреднение результатов измерений..
        /// </summary>
        internal static string AveragingText {
            get {
                return ResourceManager.GetString("AveragingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt; Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рассчитать.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетная тарировка.
        /// </summary>
        internal static string CalculatedCalibration {
            get {
                return ResourceManager.GetString("CalculatedCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарировка.
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении CSV файла.
        /// </summary>
        internal static string CSVReadingFileError {
            get {
                return ResourceManager.GetString("CSVReadingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий детектор: .
        /// </summary>
        internal static string CurrentDetector {
            get {
                return ResourceManager.GetString("CurrentDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зеленый цвет детектора обозначает стабильный уровень(объем) - можно добавлять порцию.
        ///Красный цвет детектора обозначает нестабильный уровень(объем) - порцию добавлять не рекомендуется..
        /// </summary>
        internal static string CurrentDetectorText {
            get {
                return ResourceManager.GetString("CurrentDetectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - Диаметр цистрерны, мм..
        /// </summary>
        internal static string DiameterOfTheCistron {
            get {
                return ResourceManager.GetString("DiameterOfTheCistron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстояние от датчика до дна бака.
        /// </summary>
        internal static string DistanceFromTheSensorToTheBottomOfTheTank {
            get {
                return ResourceManager.GetString("DistanceFromTheSensorToTheBottomOfTheTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D, мм: .
        /// </summary>
        internal static string Dmm {
            get {
                return ResourceManager.GetString("Dmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E, мм: .
        /// </summary>
        internal static string Emm {
            get {
                return ResourceManager.GetString("Emm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входные данные.
        /// </summary>
        internal static string EntryData {
            get {
                return ResourceManager.GetString("EntryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка в процессе удаленного обновления, проверьте подключение к интернету и повторите попытку, если ошибка повторится, обратитесь в отдел технической поддержки..
        /// </summary>
        internal static string ErrorWhileUpdating {
            get {
                return ResourceManager.GetString("ErrorWhileUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия аппаратной части: .
        /// </summary>
        internal static string HardwareVersion {
            get {
                return ResourceManager.GetString("HardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H, мм: .
        /// </summary>
        internal static string Hmm {
            get {
                return ResourceManager.GetString("Hmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как ввести данные?.
        /// </summary>
        internal static string HowToEnterData {
            get {
                return ResourceManager.GetString("HowToEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - Длинна эллиптической боковины, мм..
        /// </summary>
        internal static string LengthOfEllipticalSidewall {
            get {
                return ResourceManager.GetString("LengthOfEllipticalSidewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - Длина цилиндрической части цистерны, мм..
        /// </summary>
        internal static string LengthOfTheCylindricalPartOfTheTank {
            get {
                return ResourceManager.GetString("LengthOfTheCylindricalPartOfTheTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CХЕМА ИЗМЕРЕНИЙ В ММ.
        /// </summary>
        internal static string MeasurementScheme {
            get {
                return ResourceManager.GetString("MeasurementScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не все поля заполнены!.
        /// </summary>
        internal static string NotAllFieldsFilledIn {
            get {
                return ResourceManager.GetString("NotAllFieldsFilledIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас не последняя версия прошивки. Хотите обновить?.
        /// </summary>
        internal static string NotLastFirmwsareVer {
            get {
                return ResourceManager.GetString("NotLastFirmwsareVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порция в л: .
        /// </summary>
        internal static string PortionInl {
            get {
                return ResourceManager.GetString("PortionInl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочитать из файла.
        /// </summary>
        internal static string ReadFromFile {
            get {
                return ResourceManager.GetString("ReadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить запись.
        /// </summary>
        internal static string RemoveTheRecord {
            get {
                return ResourceManager.GetString("RemoveTheRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить в файл.
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении файла.
        /// </summary>
        internal static string SavingFileError {
            get {
                return ResourceManager.GetString("SavingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите нужный для вас порт: .
        /// </summary>
        internal static string SelectThePortYouNeed {
            get {
                return ResourceManager.GetString("SelectThePortYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип датчиика: .
        /// </summary>
        internal static string SenorType {
            get {
                return ResourceManager.GetString("SenorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес датчика: .
        /// </summary>
        internal static string SensorAddress {
            get {
                return ResourceManager.GetString("SensorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес датчика в сети. .
        /// </summary>
        internal static string SensorAddressText {
            get {
                return ResourceManager.GetString("SensorAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура датчика.
        /// </summary>
        internal static string SensorTemperature {
            get {
                return ResourceManager.GetString("SensorTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип датчиика: .
        /// </summary>
        internal static string SensorType {
            get {
                return ResourceManager.GetString("SensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серийный номер: .
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить заводские настройки.
        /// </summary>
        internal static string SetFactorySettings {
            get {
                return ResourceManager.GetString("SetFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление ПО.
        /// </summary>
        internal static string SoftwareUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия прошивки: .
        /// </summary>
        internal static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка файла!.
        /// </summary>
        internal static string strFileError {
            get {
                return ResourceManager.GetString("strFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аппаратная версия не совпадает!.
        /// </summary>
        internal static string strHardwareVersionNotMatch {
            get {
                return ResourceManager.GetString("strHardwareVersionNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не предназначен для данного типа оборудования!.
        /// </summary>
        internal static string strIsNotIntended {
            get {
                return ResourceManager.GetString("strIsNotIntended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех!.
        /// </summary>
        internal static string strSuccess {
            get {
                return ResourceManager.GetString("strSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление прошло успешно!.
        /// </summary>
        internal static string strUpdateSuccessful {
            get {
                return ResourceManager.GetString("strUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл успешно сохранен!.
        /// </summary>
        internal static string SuccesfullySavedFile {
            get {
                return ResourceManager.GetString("SuccesfullySavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Терминатор.
        /// </summary>
        internal static string Terminator {
            get {
                return ResourceManager.GetString("Terminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включение режима согласования волновых сопротивлений шины данных RS485.
        ///При установке этой опции в шину передачи данных со стороны прибора включается согласующее сопротивление терминатором 120 Ом. 
        ///Активируется только для двух конечных устройств всей шины RS485..
        /// </summary>
        internal static string TerminatorText {
            get {
                return ResourceManager.GetString("TerminatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость передачи: .
        /// </summary>
        internal static string TransmissionSpeed {
            get {
                return ResourceManager.GetString("TransmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость передачи сообщений по интерфейсу RS485. 
        ///Может изменяться в пределах от 19200 до 115200. 
        ///По умолчанию значение скорости установлено равным 19200..
        /// </summary>
        internal static string TransmissionSpeedText {
            get {
                return ResourceManager.GetString("TransmissionSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтяжка.
        /// </summary>
        internal static string Tuck {
            get {
                return ResourceManager.GetString("Tuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служит для задания устойчивого логического состояния &quot;1&quot; в периоды отсутствия обмена данными.
        ///Физическая шина &quot;A&quot; одтягивается к питанию интерфейса, шина &quot;B&quot; подтягивается к общему проводу..
        /// </summary>
        internal static string TuckText {
            get {
                return ResourceManager.GetString("TuckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить прошивку.
        /// </summary>
        internal static string UpdateFirmware {
            get {
                return ResourceManager.GetString("UpdateFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление ПО.
        /// </summary>
        internal static string UpdateSoftware {
            get {
                return ResourceManager.GetString("UpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкция по обновлению / список прошивок.
        /// </summary>
        internal static string UpgradeInstructionsFirmwareList {
            get {
                return ResourceManager.GetString("UpgradeInstructionsFirmwareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступные тип для загрузки файла (csv, xls, xlsx) .
        /// </summary>
        internal static string UploadFileAvailableTypes {
            get {
                return ResourceManager.GetString("UploadFileAvailableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файл.
        /// </summary>
        internal static string UploadXlsFile {
            get {
                return ResourceManager.GetString("UploadXlsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение мм.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение N: .
        /// </summary>
        internal static string ValueN {
            get {
                return ResourceManager.GetString("ValueN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное значение показаний уровня(объема). 
        ///По умолчанию значение установлено 1023..
        /// </summary>
        internal static string ValueNText {
            get {
                return ResourceManager.GetString("ValueNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объем.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объем л.
        /// </summary>
        internal static string VolumeL {
            get {
                return ResourceManager.GetString("VolumeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записать в датчик.
        /// </summary>
        internal static string WriteToTheSensor {
            get {
                return ResourceManager.GetString("WriteToTheSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении XLS файла.
        /// </summary>
        internal static string XLSReadingFileeError {
            get {
                return ResourceManager.GetString("XLSReadingFileeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении XLSX файла.
        /// </summary>
        internal static string XLSXReadingFileeError {
            get {
                return ResourceManager.GetString("XLSXReadingFileeError", resourceCulture);
            }
        }
    }
}
