//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorMWS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfiguratorMWS.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись.
        /// </summary>
        internal static string AddARecord {
            get {
                return ResourceManager.GetString("AddARecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние в строке, которую вы собираетесь добавить, больше предыдущего. Вы уверены, что хотите добавить строку?.
        /// </summary>
        internal static string AddingRowInCalibrationTableWarningText {
            get {
                return ResourceManager.GetString("AddingRowInCalibrationTableWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усреднение: .
        /// </summary>
        internal static string Averaging {
            get {
                return ResourceManager.GetString("Averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временной интервал, за который производится усреднение результатов измерений..
        /// </summary>
        internal static string AveragingText {
            get {
                return ResourceManager.GetString("AveragingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мертвая зона.
        /// </summary>
        internal static string BlindSpot {
            get {
                return ResourceManager.GetString("BlindSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчитать.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчетная тарировка.
        /// </summary>
        internal static string CalculatedCalibration {
            get {
                return ResourceManager.GetString("CalculatedCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарировка.
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте подключение к интернету!.
        /// </summary>
        internal static string CheckInternetConnection {
            get {
                return ResourceManager.GetString("CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключен.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вероятнее всего вы подключились к неверному порту.
        /// </summary>
        internal static string ConnectedToTheWrongPort {
            get {
                return ResourceManager.GetString("ConnectedToTheWrongPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при чтении CSV файла.
        /// </summary>
        internal static string CSVReadingFileError {
            get {
                return ResourceManager.GetString("CSVReadingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий детектор: .
        /// </summary>
        internal static string CurrentDetector {
            get {
                return ResourceManager.GetString("CurrentDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зеленый цвет детектора обозначает стабильный уровень(объем) - можно добавлять порцию.
        ///Красный цвет детектора обозначает нестабильный уровень(объем) - порцию добавлять не рекомендуется..
        /// </summary>
        internal static string CurrentDetectorText {
            get {
                return ResourceManager.GetString("CurrentDetectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Диаметр цистерны, мм..
        /// </summary>
        internal static string DiameterOfTheCistron {
            get {
                return ResourceManager.GetString("DiameterOfTheCistron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расстояние от датчика до дна бака.
        /// </summary>
        internal static string DistanceFromTheSensorToTheBottomOfTheTank {
            get {
                return ResourceManager.GetString("DistanceFromTheSensorToTheBottomOfTheTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D, мм: .
        /// </summary>
        internal static string Dmm {
            get {
                return ResourceManager.GetString("Dmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E, мм: .
        /// </summary>
        internal static string Emm {
            get {
                return ResourceManager.GetString("Emm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входные данные.
        /// </summary>
        internal static string EntryData {
            get {
                return ResourceManager.GetString("EntryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка в процессе удаленного обновления, проверьте подключение к интернету и повторите попытку, если ошибка повторится, обратитесь в отдел технической поддержки..
        /// </summary>
        internal static string ErrorWhileUpdating {
            get {
                return ResourceManager.GetString("ErrorWhileUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка записи в порт.
        /// </summary>
        internal static string ErrorWhileWritingToPort {
            get {
                return ResourceManager.GetString("ErrorWhileWritingToPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заводские настройки установлены.
        /// </summary>
        internal static string FactorySettingsHaveBeenRestored {
            get {
                return ResourceManager.GetString("FactorySettingsHaveBeenRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия аппаратной части: .
        /// </summary>
        internal static string HardwareVersion {
            get {
                return ResourceManager.GetString("HardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H, мм: .
        /// </summary>
        internal static string Hmm {
            get {
                return ResourceManager.GetString("Hmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как ввести данные?.
        /// </summary>
        internal static string HowToEnterData {
            get {
                return ResourceManager.GetString("HowToEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить обновление?.
        /// </summary>
        internal static string InstallTheUpdate {
            get {
                return ResourceManager.GetString("InstallTheUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помехи.
        /// </summary>
        internal static string Interference {
            get {
                return ResourceManager.GetString("Interference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль!.
        /// </summary>
        internal static string InvalidLoginOrPassword {
            get {
                return ResourceManager.GetString("InvalidLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л.
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Длина эллиптической боковины, мм..
        /// </summary>
        internal static string LengthOfEllipticalSidewall {
            get {
                return ResourceManager.GetString("LengthOfEllipticalSidewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Длина цилиндрической части цистерны, мм..
        /// </summary>
        internal static string LengthOfTheCylindricalPartOfTheTank {
            get {
                return ResourceManager.GetString("LengthOfTheCylindricalPartOfTheTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CХЕМА ИЗМЕРЕНИЙ В ММ.
        /// </summary>
        internal static string MeasurementScheme {
            get {
                return ResourceManager.GetString("MeasurementScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мм.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все поля заполнены!.
        /// </summary>
        internal static string NotAllFieldsFilledIn {
            get {
                return ResourceManager.GetString("NotAllFieldsFilledIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас не последняя версия прошивки. Хотите обновить?.
        /// </summary>
        internal static string NotLastFirmwsareVer {
            get {
                return ResourceManager.GetString("NotLastFirmwsareVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порция в л: .
        /// </summary>
        internal static string PortionInl {
            get {
                return ResourceManager.GetString("PortionInl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочитать из файла.
        /// </summary>
        internal static string ReadFromFile {
            get {
                return ResourceManager.GetString("ReadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись.
        /// </summary>
        internal static string RemoveTheRecord {
            get {
                return ResourceManager.GetString("RemoveTheRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в файл.
        /// </summary>
        internal static string SaveToFile {
            get {
                return ResourceManager.GetString("SaveToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при сохранении файла.
        /// </summary>
        internal static string SavingFileError {
            get {
                return ResourceManager.GetString("SavingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите нужный для вас порт: .
        /// </summary>
        internal static string SelectThePortYouNeed {
            get {
                return ResourceManager.GetString("SelectThePortYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип датчиика: .
        /// </summary>
        internal static string SenorType {
            get {
                return ResourceManager.GetString("SenorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес датчика: .
        /// </summary>
        internal static string SensorAddress {
            get {
                return ResourceManager.GetString("SensorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес датчика в сети. .
        /// </summary>
        internal static string SensorAddressText {
            get {
                return ResourceManager.GetString("SensorAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура датчика.
        /// </summary>
        internal static string SensorTemperature {
            get {
                return ResourceManager.GetString("SensorTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип датчиика: .
        /// </summary>
        internal static string SensorType {
            get {
                return ResourceManager.GetString("SensorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серийный номер: .
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить заводские настройки.
        /// </summary>
        internal static string SetFactorySettings {
            get {
                return ResourceManager.GetString("SetFactorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление ПО.
        /// </summary>
        internal static string SoftwareUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия прошивки: .
        /// </summary>
        internal static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стабилен.
        /// </summary>
        internal static string Stable {
            get {
                return ResourceManager.GetString("Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка файла!.
        /// </summary>
        internal static string strFileError {
            get {
                return ResourceManager.GetString("strFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппаратная версия не совпадает!.
        /// </summary>
        internal static string strHardwareVersionNotMatch {
            get {
                return ResourceManager.GetString("strHardwareVersionNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не предназначен для данного типа оборудования!.
        /// </summary>
        internal static string strIsNotIntended {
            get {
                return ResourceManager.GetString("strIsNotIntended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех!.
        /// </summary>
        internal static string strSuccess {
            get {
                return ResourceManager.GetString("strSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление прошло успешно!.
        /// </summary>
        internal static string strUpdateSuccessful {
            get {
                return ResourceManager.GetString("strUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение!.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно сохранен!.
        /// </summary>
        internal static string SuccesfullySavedFile {
            get {
                return ResourceManager.GetString("SuccesfullySavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминатор.
        /// </summary>
        internal static string Terminator {
            get {
                return ResourceManager.GetString("Terminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включение режима согласования волновых сопротивлений шины данных RS485.
        ///При установке этой опции в шину передачи данных со стороны прибора включается согласующее сопротивление терминалом 120 Ом. 
        ///Активируется только для двух конечных устройств всей шины RS485..
        /// </summary>
        internal static string TerminatorText {
            get {
                return ResourceManager.GetString("TerminatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость передачи: .
        /// </summary>
        internal static string TransmissionSpeed {
            get {
                return ResourceManager.GetString("TransmissionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость передачи сообщений по интерфейсу RS485. 
        ///Может изменяться в пределах от 19200 до 115200. 
        ///По умолчанию значение скорости установлено равным 19200..
        /// </summary>
        internal static string TransmissionSpeedText {
            get {
                return ResourceManager.GetString("TransmissionSpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтяжка.
        /// </summary>
        internal static string Tuck {
            get {
                return ResourceManager.GetString("Tuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служит для установки устойчивого логического состояния &quot;1&quot; в периоды отсутствия обмена данными.
        ///Физическая шина &quot;A&quot; подтягивается к питанию интерфейса, шина &quot;B&quot; подтягивается к общему проводу..
        /// </summary>
        internal static string TuckText {
            get {
                return ResourceManager.GetString("TuckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нестабилен.
        /// </summary>
        internal static string Unstable {
            get {
                return ResourceManager.GetString("Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлен.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить прошивку.
        /// </summary>
        internal static string UpdateFirmware {
            get {
                return ResourceManager.GetString("UpdateFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление ПО.
        /// </summary>
        internal static string UpdateSoftware {
            get {
                return ResourceManager.GetString("UpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция по обновлению / список прошивок.
        /// </summary>
        internal static string UpgradeInstructionsFirmwareList {
            get {
                return ResourceManager.GetString("UpgradeInstructionsFirmwareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные тип для загрузки файла (csv, xls, xlsx) .
        /// </summary>
        internal static string UploadFileAvailableTypes {
            get {
                return ResourceManager.GetString("UploadFileAvailableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить файл.
        /// </summary>
        internal static string UploadXlsFile {
            get {
                return ResourceManager.GetString("UploadXlsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение N.
        /// </summary>
        internal static string ValN {
            get {
                return ResourceManager.GetString("ValN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение, мм.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение N: .
        /// </summary>
        internal static string ValueN {
            get {
                return ResourceManager.GetString("ValueN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное значение показаний уровня(объема). 
        ///По умолчанию значение установлено 1023..
        /// </summary>
        internal static string ValueNText {
            get {
                return ResourceManager.GetString("ValueNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объем, л.
        /// </summary>
        internal static string VolumeL {
            get {
                return ResourceManager.GetString("VolumeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать в датчик.
        /// </summary>
        internal static string WriteToTheSensor {
            get {
                return ResourceManager.GetString("WriteToTheSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при чтении XLS файла.
        /// </summary>
        internal static string XLSReadingFileeError {
            get {
                return ResourceManager.GetString("XLSReadingFileeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при чтении XLSX файла.
        /// </summary>
        internal static string XLSXReadingFileeError {
            get {
                return ResourceManager.GetString("XLSXReadingFileeError", resourceCulture);
            }
        }
    }
}
